# Wine Quality Prediction  using Support Vector Machine

# Import Library


In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Import Data

In [6]:
df =  pd.read_csv('https://github.com/YBIFoundation/Dataset/raw/main/WhiteWineQuality.csv',sep=";")
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [7]:
df.shape

(4898, 12)

# Getting Information about DataFrame

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         4898 non-null   float64
 1   volatile acidity      4898 non-null   float64
 2   citric acid           4898 non-null   float64
 3   residual sugar        4898 non-null   float64
 4   chlorides             4898 non-null   float64
 5   free sulfur dioxide   4898 non-null   float64
 6   total sulfur dioxide  4898 non-null   float64
 7   density               4898 non-null   float64
 8   pH                    4898 non-null   float64
 9   sulphates             4898 non-null   float64
 10  alcohol               4898 non-null   float64
 11  quality               4898 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 459.3 KB


In [10]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    4898.000000       4898.000000  4898.000000     4898.000000   
mean        6.854788          0.278241     0.334192        6.391415   
std         0.843868          0.100795     0.121020        5.072058   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.300000          0.210000     0.270000        1.700000   
50%         6.800000          0.260000     0.320000        5.200000   
75%         7.300000          0.320000     0.390000        9.900000   
max        14.200000          1.100000     1.660000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  4898.000000          4898.000000           4898.000000  4898.000000   
mean      0.045772            35.308085            138.360657     0.994027   
std       0.021848            17.007137             42.498065     0.002991   
min       0.009000             2.000000              9.000000     0.987110   
25%       0.036000            23.000000            108.000000     0.991723   
50%       0.043000            34.000000            134.000000     0.993740   
75%       0.050000            46.000000            167.000000     0.996100   
max       0.346000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol      quality  
count  4898.000000  4898.000000  4898.000000  4898.000000  
mean      3.188267     0.489847    10.514267     5.877909  
std       0.151001     0.114126     1.230621     0.885639  
min       2.720000     0.220000     8.000000     3.000000  
25%       3.090000     0.410000     9.500000     5.000000  
50%       3.180000     0.470000    10.400000     6.000000  
75%       3.280000     0.550000    11.400000     6.000000  
max       3.820000     1.080000    14.200000     9.000000

In [11]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

# Defining X an y Variables

In [20]:
X = df.drop(['quality'],axis=1)
X.shape

(4898, 11)

In [17]:
y=df['quality']
y.shape

(4898,)

# Standardization

In [24]:
from sklearn.preprocessing import StandardScaler

In [25]:
ss= StandardScaler()

In [26]:
X = ss.fit_transform(X)

In [27]:
X

array([[ 1.72096961e-01, -8.17699008e-02,  2.13280202e-01, ...,
        -1.24692128e+00, -3.49184257e-01, -1.39315246e+00],
       [-6.57501128e-01,  2.15895632e-01,  4.80011213e-02, ...,
         7.40028640e-01,  1.34184656e-03, -8.24275678e-01],
       [ 1.47575110e+00,  1.74519434e-02,  5.43838363e-01, ...,
         4.75101984e-01, -4.36815783e-01, -3.36667007e-01],
       ...,
       [-4.20473102e-01, -3.79435433e-01, -1.19159198e+00, ...,
        -1.31315295e+00, -2.61552731e-01, -9.05543789e-01],
       [-1.60561323e+00,  1.16673788e-01, -2.82557040e-01, ...,
         1.00495530e+00, -9.62604939e-01,  1.85757201e+00],
       [-1.01304317e+00, -6.77100966e-01,  3.78559282e-01, ...,
         4.75101984e-01, -1.48839409e+00,  1.04489089e+00]])

# Train Test Split

In [28]:
from sklearn.model_selection import train_test_split

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3 , stratify=y, random_state=2529)

In [33]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape 

((3428, 11), (1470, 11), (3428,), (1470,))

# Model Training

In [34]:
from sklearn.svm import SVC

In [35]:
svc=SVC()

In [36]:
svc.fit(X_train,y_train)

SVC()

# Model Prediction

In [37]:
y_pred = svc.predict(X_test)

In [38]:
y_pred.shape

(1470,)

In [39]:
y_pred

array([5, 7, 5, ..., 5, 5, 5], dtype=int64)

# Model Evaluation 

In [41]:
from sklearn.metrics import confusion_matrix , classification_report

In [43]:
print(confusion_matrix(y_test,y_pred))

[[  0   0   1   5   0   0   0]
 [  0   2  25  22   0   0   0]
 [  0   3 273 160   1   0   0]
 [  0   0 122 515  23   0   0]
 [  0   0   6 191  67   0   0]
 [  0   0   0  39  14   0   0]
 [  0   0   0   0   1   0   0]]


In [44]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         6
           4       0.40      0.04      0.07        49
           5       0.64      0.62      0.63       437
           6       0.55      0.78      0.65       660
           7       0.63      0.25      0.36       264
           8       0.00      0.00      0.00        53
           9       0.00      0.00      0.00         1

    accuracy                           0.58      1470
   macro avg       0.32      0.24      0.25      1470
weighted avg       0.57      0.58      0.55      1470



C:\Users\P.KISHOR\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\P.KISHOR\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\P.KISHOR\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Get Model re-run with 2 class created  for wine Quality

Wine  Quality  3,4,5 labelled as 0 

Wine  Quality  6,7,8,9 labelled as 1

In [47]:
y = df['quality'].apply(lambda y_value: 1 if y_value<6 else 0)

In [49]:
y.value_counts()

0    3258
1    1640
Name: quality, dtype: int64

# Train Test Split

In [50]:
from sklearn.model_selection import train_test_split

In [51]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3 , stratify=y, random_state=2529)

In [52]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape 

((3428, 11), (1470, 11), (3428,), (1470,))

# Model Training

In [53]:
from sklearn.svm import SVC

In [54]:
svc=SVC()

In [55]:
svc.fit(X_train,y_train)

SVC()

# Model Prediction

In [56]:
y_pred = svc.predict(X_test)

In [57]:
y_pred.shape

(1470,)

In [58]:
y_pred

array([0, 0, 1, ..., 0, 1, 1], dtype=int64)

# Model Evaluation

In [59]:
from sklearn.metrics import confusion_matrix , classification_report

In [60]:
print(confusion_matrix(y_test,y_pred))

[[849 129]
 [200 292]]


In [61]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.81      0.87      0.84       978
           1       0.69      0.59      0.64       492

    accuracy                           0.78      1470
   macro avg       0.75      0.73      0.74      1470
weighted avg       0.77      0.78      0.77      1470



# Future Prediction

In [64]:
df_new  = df.sample(1)
df_new.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
3755            7.8              0.19         0.32             7.4      0.015   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
3755                 47.0                 124.0  0.99278  2.99       0.39   

      alcohol  quality  
3755     11.0        6

In [63]:
df_new.shape

(1, 12)

In [65]:
X_new  = df_new.drop(['quality'], axis=1)

In [66]:
X_new = ss.fit_transform(X_new)

In [67]:
y_pred_new = svc.predict(X_new)

In [68]:
y_pred_new

array([0], dtype=int64)